public enum ItemType {
    RAWMEAT, SKIN, BOW, ARROW, KNIFE,
    WOOL, MILK, POTATO, CARROT, SHOVEL,
    PLOW, BUCKET, SHEARS, CART, WOOD,
    AXE, HAMMER, METAL, PICKAXE, MEAT, BREAD,
    CLOTHES, STRING
}
